CREATE TABLE KEYS_SYSTEM(
	VALORGUID VARCHAR(100) NOT NULL PRIMARY KEY,
    ATIVO CHAR(1) DEFAULT '0' NOT NULL
)

CREATE TABLE CLIENTESINTERESSADOS (
CNPJ  VARCHAR(20)  DEFAULT '' NOT NULL , 
RAZAOSOCIAL  VARCHAR(500)  DEFAULT '' NOT NULL , 
NOMEFANTASIA  VARCHAR(500) , 
EMAIL  VARCHAR(200)  DEFAULT '' NOT NULL , 
TELEFONE  VARCHAR(30)  DEFAULT '' NOT NULL 
,  PRIMARY KEY ( CNPJ  )
)

CREATE TABLE INSTALADORES (
CODIGOPROJETO  INTEGER  DEFAULT 0 NOT NULL , 
VERSAO  VARCHAR(7) , 
CAMINHO  VARCHAR(1000)  DEFAULT '' NOT NULL 
,  PRIMARY KEY ( CODIGOPROJETO , VERSAO  )
)

CREATE TABLE USUARIO (
CODIGO  INTEGER , 
LOGIN  VARCHAR(50)  DEFAULT '' NOT NULL , 
SENHA  VARCHAR(16)  DEFAULT '' NOT NULL , 
ADMINISTRADOR  CHAR(1)  DEFAULT '0' NOT NULL , 
DESENVOLVEDOR  CHAR(1)  DEFAULT '0' NOT NULL , 
EMAIL  VARCHAR(200)  DEFAULT '' NOT NULL 
,  PRIMARY KEY ( CODIGO  )
)

CREATE TABLE SUPORTECODIGO (
CODIGO  INTEGER 
,  PRIMARY KEY ( CODIGO  )
)

CREATE TABLE TIPOSUPORTE (
CODIGO  INTEGER  DEFAULT 0 NOT NULL , 
DESCRICAO  VARCHAR(1000)  DEFAULT '' NOT NULL 
)

CREATE TABLE SUPORTERESPOSTAS (
CODIGO  INTEGER  DEFAULT 0 NOT NULL , 
CODIGOSUPORTE  INTEGER  DEFAULT 0 NOT NULL , 
RESPOSTA  VARCHAR(1000)  DEFAULT '' NOT NULL 
)

CREATE TABLE SUPORTE (
CODIGO  INTEGER , 
CNPJ  VARCHAR(18)  DEFAULT '' NOT NULL , 
STATUS  CHAR(1)  DEFAULT '0' NOT NULL , 
TEXTO  VARCHAR(2000)  DEFAULT '' NOT NULL , 
TIPOSUPORTE  INTEGER  DEFAULT 0 NOT NULL , 
TITULO  INTEGER  DEFAULT 0 NOT NULL , 
DATAABERTURA  VARCHAR(0)  DEFAULT '' NOT NULL 
,  PRIMARY KEY ( CODIGO  )
)

CREATE TABLE RESPOSTACODIGO (
CODIGO  INTEGER  DEFAULT 0 NOT NULL 
,  PRIMARY KEY ( CODIGO  )
)

CREATE TABLE ACESSO_KEY (
DATA_ACESSO  VARCHAR(18) , 
IP  VARCHAR(100)  DEFAULT '' NOT NULL , 
CHAVE  VARCHAR(100)  DEFAULT '' NOT NULL 
)

ALTER TABLE KEYS_SYSTEM ADD PC_NAME VARCHAR(300) NOT NULL DEFAULT '-';