CREATE TABLE KEYS_SYSTEM(
	VALORGUID VARCHAR(100) NOT NULL PRIMARY KEY,
    ATIVO CHAR(1) DEFAULT '0' NOT NULL
)

CREATE TABLE CLIENTESINTERESSADOS (
CNPJ  VARCHAR(20)  DEFAULT '' NOT NULL , 
RAZAOSOCIAL  VARCHAR(500)  DEFAULT '' NOT NULL , 
NOMEFANTASIA  VARCHAR(500) , 
EMAIL  VARCHAR(200)  DEFAULT '' NOT NULL , 
TELEFONE  VARCHAR(30)  DEFAULT '' NOT NULL 
,  PRIMARY KEY ( CNPJ  )
)

CREATE TABLE INSTALADORES (
CODIGOPROJETO  INTEGER  DEFAULT 0 NOT NULL , 
VERSAO  VARCHAR(7) , 
CAMINHO  VARCHAR(1000)  DEFAULT '' NOT NULL 
,  PRIMARY KEY ( CODIGOPROJETO , VERSAO  )
)
